### ISSUE TITLE
Question about 'optional' branches

### ISSUE THREAD

**Issue by deltamualpha** [ericgj/metalsmith-branch#1]
I'm curious: can this plugin do switching based on arbitrary true/false for a workflow? i.e. could I use this plugin to add a --watch flag to my metalsmith build that only activates a plugin if that's passed to it (like a gulp flag)?

**Comment by ericgj** [comment]
I'm not sure I understand what you mean, but if you have the flag in scope, I guess you could, sure. The function passed into this plugin, i.e. `branch(fn)` is run on each file, but can be anything, not necessarily related to file info or order.  

NB. I haven't used metalsmith in quite awhile, so this plugin probably needs to be updated to work with the latest version.

**Comment by deltamualpha** [comment]
I ended up writing my own plugin to solve this problem: https://github.com/deltamualpha/metalsmith-if.
